# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = Mang1c.o Danhsachsinhvien.o
LINKOBJ  = Mang1c.o Danhsachsinhvien.o
LIBS     = -L"D:/Devc1/Dev-Cpp/MinGW64/lib" -L"D:/Devc1/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows -g3
INCS     = -I"D:/Devc1/Dev-Cpp/MinGW64/include" -I"D:/Devc1/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Devc1/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Devc1/Dev-Cpp/MinGW64/include" -I"D:/Devc1/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Devc1/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Devc1/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = project.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Mang1c.o: Mang1c.cpp
	$(CPP) -c Mang1c.cpp -o Mang1c.o $(CXXFLAGS)

Danhsachsinhvien.o: Danhsachsinhvien.cpp
	$(CPP) -c Danhsachsinhvien.cpp -o Danhsachsinhvien.o $(CXXFLAGS)
